# Generated by Django 2.2.1 on 2019-07-04 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.IntegerField()),
                ('last', models.IntegerField()),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('steps', models.IntegerField()),
                ('ended', models.BooleanField()),
            ],
        ),
    ]
