# Generated by Django 2.2.1 on 2019-07-05 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='ended',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='first',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='last',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='steps',
            field=models.IntegerField(default=0),
        ),
    ]
