# Generated by Django 2.2.2 on 2019-07-06 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_auto_20190705_1201'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameStat',
            fields=[
                ('game_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_page_id', models.IntegerField(default=0)),
                ('end_page_id', models.IntegerField(default=0)),
                ('steps', models.IntegerField(default=0)),
                ('finished', models.BooleanField(default=False)),
                ('start_time', models.DateTimeField(null=True)),
                ('last_action_time', models.DateTimeField()),
            ],
        ),
    ]
