# Generated by Django 2.2.2 on 2019-07-06 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0005_auto_20190706_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='name',
            field=models.CharField(default='Анонимно', max_length=30),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='text',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
