# Generated by Django 2.2.1 on 2019-07-07 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0006_auto_20190706_1858'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('game_id', models.IntegerField()),
                ('from_page_id', models.IntegerField(null=True)),
                ('to_page_id', models.IntegerField()),
                ('time', models.DateTimeField()),
                ('turn_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
