# Generated by Django 2.2.3 on 2019-07-15 08:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0008_auto_20190709_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamePair',
            fields=[
                ('start_page_id', models.IntegerField(default=0)),
                ('end_page_id', models.IntegerField(default=0)),
                ('pair_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.DeleteModel(
            name='GameStat',
        ),
        migrations.RenameField(
            model_name='turn',
            old_name='to_page_id',
            new_name='end_page_id',
        ),
        migrations.RenameField(
            model_name='turn',
            old_name='from_page_id',
            new_name='start_page_id',
        ),
        migrations.RemoveField(
            model_name='game',
            name='ended',
        ),
        migrations.RemoveField(
            model_name='game',
            name='first',
        ),
        migrations.RemoveField(
            model_name='game',
            name='id',
        ),
        migrations.RemoveField(
            model_name='game',
            name='last',
        ),
        migrations.RemoveField(
            model_name='game',
            name='session_id',
        ),
        migrations.AddField(
            model_name='game',
            name='current_page_id',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='end_page_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='game_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='last_action_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 15, 11, 52, 55, 395695)),
        ),
        migrations.AddField(
            model_name='game',
            name='start_page_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='game_pair',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wiki.GamePair'),
        ),
    ]
