# Generated by Django 2.2.1 on 2019-07-10 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0008_auto_20190709_1250'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Game',
        ),
    ]
