# Generated by Django 2.2.3 on 2019-07-17 05:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0009_auto_20190715_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='end_page_id',
        ),
        migrations.RemoveField(
            model_name='game',
            name='start_page_id',
        ),
        migrations.RemoveField(
            model_name='turn',
            name='end_page_id',
        ),
        migrations.RemoveField(
            model_name='turn',
            name='start_page_id',
        ),
        migrations.AddField(
            model_name='turn',
            name='game_pair',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wiki.GamePair'),
        ),
        migrations.AlterField(
            model_name='game',
            name='last_action_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 17, 8, 19, 18, 590489)),
        ),
    ]
