# Generated by Django 2.2.1 on 2019-07-10 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0009_delete_game'),
    ]

    operations = [
        migrations.RenameModel(old_name='GameStat', new_name='Game'),
        migrations.RemoveField(model_name='Game', name='finished'),
    ]
