# Generated by Django 2.2.1 on 2019-07-11 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0010_auto_20190710_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('node_id', models.AutoField(primary_key=True, serialize=False)),
                ('prev_node_id', models.IntegerField(default=None, null=True)),
                ('page_id', models.IntegerField()),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Turn',
        ),
        migrations.AddField(
            model_name='game',
            name='last_node',
            field=models.OneToOneField(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='wiki.Node'
            ),
        ),
    ]
