# Generated by Django 2.2.2 on 2019-07-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0010_auto_20190710_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGame',
            fields=[
                ('game_id', models.AutoField(primary_key=True, serialize=False)),
                ('autor_name', models.CharField(default='Анонимно', max_length=30)),
                ('from_page_id', models.IntegerField()),
                ('to_page_id', models.IntegerField()),
                ('likes', models.IntegerField(default=0)),
                ('shortest_path_len', models.IntegerField(null=True)),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
