# Generated by Django 2.2.3 on 2019-07-12 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0010_auto_20190710_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='pair_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='turn',
            name='pair_id',
            field=models.IntegerField(default=2112),
            preserve_default=False,
        ),
    ]
