# Generated by Django 2.2.2 on 2019-07-16 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0010_auto_20190710_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamePair',
            fields=[
                ('pair_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_page_id', models.IntegerField(default=0)),
                ('end_page_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='game',
            name='end_page_id',
        ),
        migrations.RemoveField(
            model_name='game',
            name='start_page_id',
        ),
        migrations.CreateModel(
            name='Trial',
            fields=[
                ('trial_id', models.AutoField(primary_key=True, serialize=False)),
                ('trial_name', models.CharField(default='испытание', max_length=200)),
                ('game_pair', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wiki.GamePair')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='game_pair',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wiki.GamePair'),
        ),
        migrations.AddField(
            model_name='turn',
            name='game_pair',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wiki.GamePair'),
        ),
    ]
