# Generated by Django 2.2.2 on 2019-07-15 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('wiki', '0010_auto_20190710_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiplayerPair',
            fields=[
                ('from_page_id', models.IntegerField()),
                ('to_page_id', models.IntegerField()),
                ('game_id', models.AutoField(primary_key=True, serialize=False)),
                ('game_key', models.CharField(default='', max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sessions.Session'),
        ),
        migrations.AddField(
            model_name='game',
            name='session_key',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='game',
            name='multiplayer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wiki.MultiplayerPair'),
        ),
    ]
