# Generated by Django 2.2.3 on 2019-07-12 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0010_auto_20190710_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='difficulty_pair_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='game',
            name='diffuculty',
            field=models.TextField(null=True),
        ),
    ]
