# Generated by Django 2.2.2 on 2019-07-17 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0011_auto_20190715_1339'),
        ('wiki', '0011_game_possible_path'),
    ]

    operations = [
    ]
