# Generated by Django 2.2.3 on 2019-07-12 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0011_auto_20190712_1354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='diffuculty',
            new_name='difficulty',
        ),
    ]
