# Generated by Django 2.2.3 on 2019-07-17 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0011_game_possible_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='surrendered',
            field=models.BooleanField(default=False),
        ),
    ]
