# Generated by Django 2.2.2 on 2019-07-12 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0011_usergame'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trial',
            fields=[
                ('game_id', models.AutoField(primary_key=True, serialize=False)),
                ('trial_name', models.CharField(default='испытание', max_length=200)),
                ('from_page_id', models.IntegerField()),
                ('to_page_id', models.IntegerField()),
            ],
        ),
    ]
