# Generated by Django 2.2.2 on 2019-07-17 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0011_auto_20190716_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_pair',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wiki.GamePair'),
        ),
    ]
