# Generated by Django 2.2.2 on 2019-07-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0011_auto_20190714_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='session_key',
            field=models.CharField(default='', max_length=128),
        ),
    ]
