# Generated by Django 2.2.3 on 2019-07-12 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0011_auto_20190712_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turn',
            name='pair_id',
        ),
    ]
