# Generated by Django 2.2.2 on 2019-07-16 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0012_trial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trial',
            old_name='game_id',
            new_name='trial_id',
        ),
    ]
