# Generated by Django 2.2.2 on 2019-07-17 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0012_create_game_pairs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='end_page_id',
        ),
        migrations.RemoveField(
            model_name='game',
            name='start_page_id',
        ),
        migrations.RemoveField(
            model_name='game',
            name='possible_path',
        ),
        migrations.AlterField(
            model_name='game',
            name='game_pair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiki.GamePair'),
        ),
        migrations.CreateModel(
            name='Trial',
            fields=[
                ('trial_id', models.AutoField(primary_key=True, serialize=False)),
                ('trial_name', models.CharField(default='испытание', max_length=200)),
                ('game_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiki.GamePair')),
            ],
        ),
    ]
