# Generated by Django 2.2.3 on 2019-07-12 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0012_remove_turn_pair_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamePair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_page_id', models.IntegerField()),
                ('to_page_id', models.IntegerField()),
                ('pair_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='game',
            name='pair_id',
        ),
    ]
