# Generated by Django 2.2.3 on 2019-07-14 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0012_auto_20190712_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='game',
            name='difficulty_pair_id',
        ),
        migrations.AddField(
            model_name='game',
            name='possible_path',
            field=models.TextField(default=''),
        ),
    ]
