# Generated by Django 2.2.2 on 2019-07-14 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('wiki', '0012_game_session_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='session_key',
        ),
        migrations.AddField(
            model_name='game',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sessions.Session'),
        ),
    ]
