# Generated by Django 2.2.2 on 2019-07-15 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0013_auto_20190714_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiplayerpair',
            name='game_key',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='multiplayerpair',
            name='game_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
