# Generated by Django 2.2.2 on 2019-07-11 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0013_auto_20190711_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='difficulty',
            field=models.IntegerField(default=0),
        ),
    ]
