# Generated by Django 2.2.3 on 2019-07-18 08:45

from django.db import migrations, models
import wiki.models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0014_game_surrendered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='steps',
        ),
        migrations.AddField(
            model_name='turn',
            name='step',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='turn',
            name='turn_type',
            field=models.CharField(choices=[(wiki.models.TurnType('direct'), 'direct'),
                                            (wiki.models.TurnType('reverse'), 'reverse')],
                                   default=wiki.models.TurnType('direct'), max_length=16),
        ),
    ]
