# Generated by Django 2.2.3 on 2019-07-18 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0014_game_surrendered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='steps',
        ),
        migrations.AddField(
            model_name='turn',
            name='is_reversed',
            field=models.BooleanField(default=False),
        ),
    ]
