# Generated by Django 2.2.3 on 2019-07-14 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0014_auto_20190714_1006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turn',
            old_name='from_page_id',
            new_name='end_page_id',
        ),
        migrations.RenameField(
            model_name='turn',
            old_name='to_page_id',
            new_name='start_page_id',
        ),
        migrations.RenameField(
            model_name='gamepair',
            old_name='from_page_id',
            new_name='start_page_id',
        ),
        migrations.RenameField(
            model_name='gamepair',
            old_name='to_page_id',
            new_name='end_page_id',
        ),
    ]
