# Generated by Django 2.2.2 on 2019-07-18 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0014_auto_20190717_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiplayerpair',
            name='game_key',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
