# Generated by Django 2.2.3 on 2019-07-18 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0015_auto_20190718_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='game_pair',
        ),
        migrations.AlterField(
            model_name='game',
            name='multiplayer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiki.MultiplayerPair'),
        ),
    ]
