# Generated by Django 2.2.2 on 2019-07-11 09:19

import annoying.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0015_auto_20190711_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='profile',
            field=annoying.fields.AutoOneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='wiki.Profile'),
        ),
    ]
