# Generated by Django 2.2.3 on 2019-07-14 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0015_auto_20190714_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamepair',
            name='end_page_id',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='gamepair',
            name='start_page_id',
            field=models.IntegerField(default=None),
        ),
    ]
