# Generated by Django 2.2.3 on 2019-07-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0016_auto_20190714_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamepair',
            name='end_page_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='gamepair',
            name='start_page_id',
            field=models.IntegerField(),
        ),
    ]
