# Generated by Django 2.2.2 on 2019-07-11 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0016_auto_20190711_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='name',
        ),
    ]
