# Generated by Django 2.2.3 on 2019-07-18 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0015_auto_20190718_1200'),
        ('wiki', '0016_auto_20190718_1250'),
    ]

    operations = [
    ]
