# Generated by Django 2.2.2 on 2019-07-18 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0017_merge_20190718_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('_difficulty', models.CharField(default='easy', max_length=10)),
                ('name', models.CharField(default='no name', max_length=16, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='user_settings',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wiki.UserSettings'),
        ),
    ]
