# Generated by Django 2.2.2 on 2019-07-18 12:54

from django.db import migrations, models
import django.db.models.deletion
import wiki.models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0017_merge_20190718_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('difficulty', models.CharField(choices=[(wiki.models.GameTypes('random'), 'random'), (wiki.models.GameTypes('easy'), 'easy'), (wiki.models.GameTypes('medium'), 'medium'), (wiki.models.GameTypes('hard'), 'hard'), (wiki.models.GameTypes('trial'), 'trial'), (wiki.models.GameTypes('by_id'), 'by_id')], default='easy', max_length=10)),
                ('name', models.CharField(default='no name', max_length=16)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='user_settings',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wiki.UserSettings'),
        ),
    ]
