# Generated by Django 2.2.4 on 2019-12-29 17:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0018_auto_20190718_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='trial',
            name='_begin',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 29, 17, 52, 45, 16434, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='trial',
            name='_length',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
