# Generated by Django 2.2.4 on 2019-12-31 07:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import wiki.models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0019_auto_20191229_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='trial',
            name='type',
            field=models.CharField(choices=[(wiki.models.TrialType('Trial'), 'Trial'),
                                            (wiki.models.TrialType('Event'), 'Event')],
                                   default=wiki.models.TrialType('Trial'), max_length=16),
        ),
        migrations.AlterField(
            model_name='trial',
            name='_begin',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 31, 7, 48, 38, 211235, tzinfo=utc)),
        ),
    ]
