# Generated by Django 2.2.4 on 2019-12-31 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0021_auto_20191231_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='vk_access_token',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
