# Generated by Django 2.2.2 on 2019-12-31 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0022_usersettings_vk_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trial',
            name='_begin',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
