# Generated by Django 2.2.4 on 2020-01-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0024_auto_20200102_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='trial',
            name='min_hops',
            field=models.IntegerField(default=4),
        ),
    ]
