# Generated by Django 2.2.4 on 2020-01-01 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0024_gamestats'),
    ]

    operations = [
        migrations.AddField(
            model_name='trial',
            name='difficulty',
            field=models.FloatField(default=0),
        ),
    ]
