# Generated by Django 2.2.4 on 2020-01-03 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0025_trial_min_hops'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trial',
            name='_begin',
            field=models.DateTimeField(),
        ),
    ]
