# Generated by Django 2.2.4 on 2020-01-01 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0025_trial_difficulty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamestats',
            old_name='tial_id',
            new_name='trial_id',
        ),
    ]
