# Generated by Django 2.2.2 on 2020-01-03 16:18

from django.db import migrations, models
import wiki.models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0026_auto_20200103_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trial',
            name='type',
            field=models.CharField(choices=[('TrialType.TRIAL', 'Trial'), ('TrialType.EVENT', 'Event')], default=wiki.models.TrialType('Trial'), max_length=16),
        ),
    ]
