# Generated by Django 2.2.4 on 2020-01-04 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0026_auto_20200103_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='curr_game_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='history_json',
            field=models.CharField(default='', max_length=512),
        ),
    ]
