# Generated by Django 2.2.4 on 2020-01-01 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0026_auto_20200101_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='rate',
            field=models.FloatField(default=0),
        ),
    ]
