# Generated by Django 2.2.2 on 2020-01-04 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0027_auto_20200103_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
