# Generated by Django 2.2.2 on 2020-01-05 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0028_auto_20200104_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='got_rate',
            field=models.BooleanField(default=False),
        ),
    ]
